# Generated by Django 2.1.5 on 2019-01-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('can_delete', 'Can delete posts.'),)},
        ),
    ]
